# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e780676452ac05503585c3755a8f33337192d6b6dc979af3767b1ace8f5dde314251d24c6d83d74a0f8f3950657b86a810d1c66c28fbeccb4711bba8a873c4a0

test:
  secret_key_base: 30ba3dbbb4d370008b5580ed68255ab632eb1ce57ba260e504965b42d292c12e09fcd5a3a6cb6ed9852e25a5fe493b6308030535651d317fb5fedf3e2add254a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
